@startuml

title YJU-capstone-team4
footer Page %page% of %lastpage%

actor 사용자 as User
actor 관리자 as Admin

control App
control Web
control 노드서버 as Node
control 크롤링서버 as Lamda


==내 동선 페이지==
alt 동선 폴더 선택 유무
else default 폴더
    User -> App : 내 동선 페이지 요청
else 폴더 선택
    User -> App : 동선 폴더 선택
activate User
        App --> App : 동선 폴더 리턴
end
        App -> Node : <font color=red>[Req] 동선 폴더 리스트 (1회)</font>, 폴더의 id 값 전달
            alt 동선 리스트 데이터 유무
                else 동선 리스트가 있을 때
                    Node --> Node : id -> 맛집 지도, 동선 리스트 \n select query
                else 동선 리스트가 없을 때
                    Node --> Node : statusCode :: 해당 리스트가 없습니다. \n select query
            end
        Node -> App : <font color=red>[Res]</font> 해당 폴더의 동선 리스트와 지도 반환
    App -> User : 내 동선 페이지 렌더링
deactivate User

==동선 배치==
User -> App : 맛집 동선 변경 (Drag & Drop)
activate User
    App -> Node : <font color=red>[Req]</font> 동선 변경 요청
        Node --> Node : 동선 \n update query
    Node -> App : <font color=red>[Res]</font> 변경된 동선 리스트와 지도 반환
App -> User : 변경된 동선을 적용하여 페이지 렌더링
deactivate User

@enduml