@startuml

title YJU-capstone-team4
footer Page %page% of %lastpage%

actor 사용자 as User
actor 관리자 as Admin

control App
control Web
control 노드서버 as Node
control 크롤링서버 as Lamda

==동선 공유 페이지==
User -> App : 동선 공유 페이지 요청
    App -> Node : <font color=red>[Req] 동선 폴더 리스트 (1회)</font>, 폴더의 id 값
        Node --> Node : [Query-Select]\n동선 지도, 해시태그 반환
    Node -> App : <font color=red>[Res]</font> 해당 폴더의 동선 지도와 지역 해시태그 반환
App -> User : 동선 공유 페이지 렌더링

==공유하기==
User -> App : 공유하기 버튼 클릭
    App -> Node : <font color=red>[Req]</font> 제목, 해시태그, 썸네일 전달
    Node --> Node : [Query-Insert]\n동선 데이터 저장
    Node -> App : <font color=red>[Res]</font> statusCode :: 해당 동선이 공유되었습니다.
App -> User : 초기 동선 검색 페이지 렌더링    

@enduml